#include "UI/Quest/VHVNavigationTrail.h"

#include "Components/InstancedStaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "Engine/World.h"
#include "GameFramework/Pawn.h"
#include "GameFramework/PlayerController.h"
#include "Materials/MaterialInterface.h"
#include "NavigationPath.h"
#include "NavigationSystem.h"
#include "UI/Quest/VHVObjectiveMarkerWidget.h"
#include "UObject/ConstructorHelpers.h"
#include "VHV.h"

AVHVNavigationTrail::AVHVNavigationTrail()
{
    PrimaryActorTick.bCanEverTick = true;
    PrimaryActorTick.TickGroup = TG_PostPhysics;
    SetCanBeDamaged(false);

    Arrows = CreateDefaultSubobject<UInstancedStaticMeshComponent>(TEXT("Arrows"));
    RootComponent = Arrows;
    Arrows->SetMobility(EComponentMobility::Movable);
    Arrows->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    Arrows->SetCastShadow(false);
    Arrows->SetCanEverAffectNavigation(false);
    Arrows->NumCustomDataFloats = 1;

    // Generated by Content/Python/build_navigation_assets.py.
    static ConstructorHelpers::FObjectFinder<UStaticMesh> ChevronMesh(TEXT("/Game/VHV_Stuff/Navigation/SM_NavChevron"));
    static ConstructorHelpers::FObjectFinder<UMaterialInterface> TrailMaterial(TEXT("/Game/VHV_Stuff/Navigation/M_NavTrail"));
    ArrowMesh = ChevronMesh.Object;
    ArrowMaterial = TrailMaterial.Object;
}

void AVHVNavigationTrail::SetObjectiveMarker(UVHVObjectiveMarkerWidget* InMarker)
{
    Marker = InMarker;
    if (!ArrowMesh || !ArrowMaterial)
    {
        UE_LOG(LogVHV, Warning, TEXT("[VHVNavigationTrail] Missing SM_NavChevron or M_NavTrail; run build_navigation_assets.py. Trail disabled."));
        return;
    }
    Arrows->SetStaticMesh(ArrowMesh);
    Arrows->SetMaterial(0, ArrowMaterial);
}

int32 AVHVNavigationTrail::GetArrowCount() const
{
    return Arrows ? Arrows->GetInstanceCount() : 0;
}

void AVHVNavigationTrail::Tick(const float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);
    TimeSinceRefresh += DeltaSeconds;

    const UVHVObjectiveMarkerWidget* MarkerWidget = Marker.Get();
    AActor* Target = MarkerWidget ? MarkerWidget->GetMarkerTarget() : nullptr;
    // Route from the player this trail belongs to (its owner), the same one the marker measures from.
    const APlayerController* PlayerController = Cast<APlayerController>(GetOwner());
    APawn* Pawn = PlayerController ? PlayerController->GetPawn() : nullptr;
    if (!ArrowMesh || !ArrowMaterial || !MarkerWidget || !MarkerWidget->IsMarkerShown() || !Target || !Pawn)
    {
        // Forget the target so the route is rebuilt at once when the marker shows again.
        ClearTrail();
        LastTarget.Reset();
        return;
    }

    const FVector Start = Pawn->GetActorLocation();
    const FVector TargetLocation = Target->GetActorLocation();
    const bool bNewTarget = Target != LastTarget.Get();
    const bool bMoved = FVector::DistSquared(Start, LastStart) > FMath::Square(50.0f)
        || FVector::DistSquared(TargetLocation, LastTargetLocation) > FMath::Square(50.0f);
    if (!bNewTarget)
    {
        if (TimeSinceRefresh < RefreshInterval)
        {
            return;
        }
        // After a failed route (e.g. the navmesh is still building) retry periodically even if nobody
        // moves; a valid route only needs updating after real movement.
        if (!bMoved && (!bRouteFailed || TimeSinceRefresh < RetryInterval))
        {
            return;
        }
    }

    TimeSinceRefresh = 0.0f;
    LastTarget = Target;
    LastStart = Start;
    LastTargetLocation = TargetLocation;

    // Aim at the walkable spot nearest the target: people and scenes can stand just off the navmesh
    // (on a platform, against a wall), and a route that ends within reach still guides the player.
    UNavigationSystemV1* NavigationSystem = FNavigationSystem::GetCurrent<UNavigationSystemV1>(GetWorld());
    FNavLocation Goal;
    const FVector GoalLocation = NavigationSystem
        && NavigationSystem->ProjectPointToNavigation(TargetLocation, Goal, FVector(GoalSearchRadius, GoalSearchRadius, 300.0f))
        ? Goal.Location : TargetLocation;
    UNavigationPath* Path = UNavigationSystemV1::FindPathToLocationSynchronously(this, Start, GoalLocation, Pawn);
    const bool bUsable = Path && Path->IsValid() && Path->PathPoints.Num() >= 2
        && (!Path->IsPartial() || FVector::Dist2D(Path->PathPoints.Last(), TargetLocation) <= GoalSearchRadius);
    bRouteFailed = !bUsable;
    if (!bUsable)
    {
        ClearTrail();
        return;
    }
    RebuildTrail(Path->PathPoints, Target);
}

void AVHVNavigationTrail::ClearTrail()
{
    TrailLength = 0.0f;
    if (Arrows && Arrows->GetInstanceCount() > 0)
    {
        Arrows->ClearInstances();
    }
}

void AVHVNavigationTrail::RebuildTrail(const TArray<FVector>& PathPoints, const AActor* IgnoredTarget)
{
    FCollisionQueryParams GroundQuery(SCENE_QUERY_STAT(VHVNavigationTrail), false, this);
    GroundQuery.AddIgnoredActor(IgnoredTarget);
    if (const APlayerController* PlayerController = Cast<APlayerController>(GetOwner()))
    {
        GroundQuery.AddIgnoredActor(PlayerController->GetPawn());
    }

    // Navmesh points float a little above the surface: drop each route corner onto the real ground
    // (a handful of traces) and let the arrows between them interpolate.
    TArray<FVector> Points = PathPoints;
    for (FVector& Point : Points)
    {
        FHitResult Hit;
        if (GetWorld()->LineTraceSingleByChannel(Hit, Point + FVector(0.0f, 0.0f, 120.0f),
                Point - FVector(0.0f, 0.0f, 250.0f), ECC_Visibility, GroundQuery))
        {
            Point.Z = Hit.ImpactPoint.Z;
        }
    }

    TArray<float> Cumulative;
    Cumulative.Reserve(Points.Num());
    Cumulative.Add(0.0f);
    for (int32 Index = 1; Index < Points.Num(); ++Index)
    {
        Cumulative.Add(Cumulative.Last() + FVector::Dist2D(Points[Index - 1], Points[Index]));
    }
    TrailLength = Cumulative.Last();

    // Space arrows back from the target so they stay put in the world while the player walks:
    // each refresh only trims or adds arrows at the player's end.
    TArray<FTransform> Transforms;
    TArray<float> DistancesToTarget;
    int32 Segment = Points.Num() - 1;
    for (float ToTarget = EndGap; ToTarget <= TrailLength - StartGap && Transforms.Num() < MaxArrows; ToTarget += ArrowSpacing)
    {
        const float Distance = TrailLength - ToTarget;
        while (Segment > 1 && Cumulative[Segment - 1] > Distance)
        {
            --Segment;
        }
        const FVector& From = Points[Segment - 1];
        const FVector& To = Points[Segment];
        const float SegmentLength = FMath::Max(Cumulative[Segment] - Cumulative[Segment - 1], KINDA_SMALL_NUMBER);
        const float Alpha = FMath::Clamp((Distance - Cumulative[Segment - 1]) / SegmentLength, 0.0f, 1.0f);
        const FVector Location = FMath::Lerp(From, To, Alpha) + FVector(0.0f, 0.0f, HoverHeight);

        // Arrows lie flat and point along the route.
        Transforms.Add(FTransform(FRotator(0.0f, (To - From).Rotation().Yaw, 0.0f), Location));
        DistancesToTarget.Add(ToTarget);
    }

    if (Transforms.IsEmpty())
    {
        // A valid route too short for arrows (the player is almost there); keep TrailLength as the route length.
        if (Arrows->GetInstanceCount() > 0)
        {
            Arrows->ClearInstances();
        }
        return;
    }
    if (Arrows->GetInstanceCount() == Transforms.Num())
    {
        Arrows->BatchUpdateInstancesTransforms(0, Transforms, true, false, true);
    }
    else
    {
        Arrows->ClearInstances();
        Arrows->AddInstances(Transforms, false, true);
    }
    // M_NavTrail runs its glow towards larger values, so store the negated distance to the target.
    for (int32 Index = 0; Index < DistancesToTarget.Num(); ++Index)
    {
        Arrows->SetCustomDataValue(Index, 0, -DistancesToTarget[Index], Index == DistancesToTarget.Num() - 1);
    }
}
